### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by tltsilveira** [meder411/MappedConvolutions#1]
Thank you for your amazing paper. Do you know when the source codes will be available for testing? Thank you again! Best.

**Comment by TzuRen** [comment]
Thank you for your amazing paper. Do you know when the source codes will be available for testing? Thank you again! Best.

**Comment by meder411** [comment]
Thank you for your interest! I have decided to push back the code release to early October. Please check back then. In the meantime, I am happy to answer any questions about the paper.

**Comment by meder411** [comment]
@trugillo @LuoJunren I have pushed the code online. Usage examples and docs will be coming in the next few days or so too. Stay tuned on that front. In the meantime, feel free to experiment with the layers.
