### ISSUE TITLE
What is the most appropriate way to upscale a feature map?

### ISSUE THREAD

**Issue by zuru** [meder411/MappedConvolutions#3]
There seem to be two possible ways to upscale a feature map:

- With a `MappedTransposeConvolution` that needs the sample map and weights to be of the same size as the input. This is similar to the conventional way of upscaling through transposed convolution (i.e. for standard PyTorch convolutions this means using the exact same arguments) as it means that the same sample map/weights used in the downscaling operation are required (similar to pooling/unpooling for example). Essentially this is achieved by using a lower order icosahedron as the target and sampling from a higher-order one.
- With a `MappedConvolution` by requesting sampling targets from a higher-order icosahedron that sample a lower order one. This is more in line with the documentation of the `vertex_to_vertex_kernel_map `function that mentions larger `order ` parameters represent downscaling whilst lower `order` parameters represent upscaling when compared to the order of the passed in icosphere.

After testing both it seems that the second option produces better results qualitatively as the first one generates outputs with sampling artifacts.

Concluding, is there any subtlety that I am missing?
Which of the two upscaling variants were used in the network used for the paper?

Thanks !

**Comment by meder411** [comment]
You are right that generally the second case gives much better qualitative results, but the first case more accurately mirrors what the standard transposed convolution does. I like to differentiate the two as "resample from" (case 2) vs. "resample to" (case 1). Alternatively you can think of them as a "gather" (case 2) vs. "scatter" (case 1) operation. 

In any case, the reason that `MappedTransposeConvolution` is not as qualitatively nice is that it is taking data at one scale and essentially spreading it around a higher scale where it may not actually fill all the space. `MappedConvolution` goes through every discrete location in the higher scale and fills it by sampling from the lower scale. It basically guarantees that there will be no holes.

In the paper the upsampling was done using `MappedTransposeConvolution` in an effort to be as analogous as possible to existing network architectures. It might be the case that a standard `MappedConvolution` might actually work better though. I haven't tested that.

I'm sorry I've been so delayed about uploading the actual networks. I can't guarantee them in the immediate future, but I'm pushing to clean up this repo in the next couple of months, and that includes pushing all the experiment code and better documented usage.

Please let me know if you have any more questions.

**Comment by zuru** [comment]
Thanks for the clarification !
